// swift-tools-version: 5.10

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Phono",
    platforms: [
//        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Phono",
            targets: ["AppModule"],
            bundleIdentifier: "Academy.Speeches",
            teamIdentifier: "ZFH4AF7HSL",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "To analyze the audio."),
                .speechRecognition(purposeString: "To analyze the recordings.")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources"),
                .copy("ML/PhonoV2.mlmodelc")
            ]
        )
    ]
)
